import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import ThemeProvider from '@/providers/theme.provider'
import MainHeader from '@/components/layout/main-header'
import MainFooter from '@/components/layout/main-footer'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'], variable: '--inter' })
const montserrat = Montserrat({ subsets: ['latin'], variable: '--montserrat' })
export const metadata: Metadata = {
  title: 'Zing7 Next.js boilerplare',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          montserrat.variable,
          'grid grid-rows-[auto_1fr_auto] min-h-[100svh]'
        )}
      >
        {/* Theme provider for dark and light themes */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* the header and the footer are passed here since they are the same on every page */}
          <MainHeader />
          {/* this is what the page.tsx file returnes */}
          {children}
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  )
}
